/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegazo;

import javax.swing.event.TableModelListener;
import javax.swing.table.TableModel;
import objects.Tablero;

/**
 *
 * @author Jimmi
 */
public class IUJuegazo extends javax.swing.JFrame {

    private Tablero tablero = new Tablero();
    /**
     * Creates new form IUJuegazo
     */
    public IUJuegazo() {
        initComponents();
        acomodarTablero();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaJuego = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaJuego.setAutoCreateRowSorter(true);
        tablaJuego.setBorder(new javax.swing.border.MatteBorder(null));
        tablaJuego.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaJuego.setToolTipText("");
        tablaJuego.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaJuego.setMaximumSize(new java.awt.Dimension(7, 7));
        tablaJuego.setMinimumSize(new java.awt.Dimension(7, 7));
        tablaJuego.setRowHeight(30);
        tablaJuego.setRowSelectionAllowed(false);
        tablaJuego.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaJuego.getTableHeader().setResizingAllowed(false);
        tablaJuego.getTableHeader().setReorderingAllowed(false);
        tablaJuego.setUpdateSelectionOnSort(false);
        tablaJuego.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(tablaJuego);
        tablaJuego.getAccessibleContext().setAccessibleName("tablero");

        jButton1.setText("Seleccionar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jButton1)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaJuego;
    // End of variables declaration//GEN-END:variables

    private void acomodarTablero() {
        tablaJuego.setValueAt("Hola", 0, 0);
    }
}
